number of parameters: 85.93M
KL Weight 10
Epoch 0
  0%|                                                                                                                                                                                                 | 0/2000 [00:00<?, ?it/s]2024-07-26 13:54:40,655 - INFO - val dataloader is fetching data, the length is 5.
Val loss:   72.79875
l1: 0.695 kl: 7.210 loss: 72.799
2024-07-26 13:54:41,813 - INFO - val dataloader is fetching data, the length is 5.
  0%|                                                                                                                                                                                                 | 0/2000 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 281, in <module>
    main(vars(parser.parse_args()))
  File "train.py", line 104, in main
    best_ckpt_info = train_bc(train_dataloader, val_dataloader, config)
  File "train.py", line 198, in train_bc
    for batch_idx, data in enumerate(train_dataloader):
  File "/home/lanzihan/miniconda3/envs/aloha/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/lanzihan/miniconda3/envs/aloha/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/lanzihan/miniconda3/envs/aloha/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/lanzihan/miniconda3/envs/aloha/lib/python3.8/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lanzihan/miniconda3/envs/aloha/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/lanzihan/miniconda3/envs/aloha/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/home/lanzihan/miniconda3/envs/aloha/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 316, in default_collate
    return collate(batch, collate_fn_map=default_collate_fn_map)
  File "/home/lanzihan/miniconda3/envs/aloha/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 173, in collate
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/lanzihan/miniconda3/envs/aloha/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 173, in <listcomp>
    return [collate(samples, collate_fn_map=collate_fn_map) for samples in transposed]  # Backwards compatibility.
  File "/home/lanzihan/miniconda3/envs/aloha/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 141, in collate
    return collate_fn_map[elem_type](batch, collate_fn_map=collate_fn_map)
  File "/home/lanzihan/miniconda3/envs/aloha/lib/python3.8/site-packages/torch/utils/data/_utils/collate.py", line 212, in collate_tensor_fn
    out = elem.new(storage).resize_(len(batch), *list(elem.size()))
RuntimeError: Trying to resize storage that is not resizable